set nocompatible
filetype off

""""" Start Plugin """""
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'itchyny/lightline.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'jiangmiao/auto-pairs'
Plugin 'fatih/vim-go'
Plugin 'othree/html5.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'chr4/nginx.vim'

call vundle#end()
filetype plugin indent on
"""""""""""""""""""""""""

""""" For lightline """""
set laststatus=2
set noshowmode
if !has('gui_running')
  set t_Co=256
endif
"""""""""""""""""""""""""


set number
syntax on
let mapleader=","
set nowrap
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set backspace=indent,eol,start
set ignorecase
set incsearch
set hlsearch
nmap <silent> <leader><space> :noh<CR>
set nobackup
set nowritebackup
set noswapfile
set novisualbell
set noerrorbells

nmap <F7> :tabprevious <CR>
nmap <F8> :tabnext <CR>
map <F7> :tabprevious <CR>
map <F8> :tabnext <CR>
imap <F7> <Esc> :tabprevious <CR>i
imap <F8> <Esc> :tabnext <CR>i
